### ISSUE TITLE
TODO Map Creation

### ISSUE THREAD

**Issue by SnenzZ** [SnenzZ/pok-mon-js-game#1]
### Map Creation with Tiled Map Editor:

- [ ] Download and Setup
- [ ] Tile Layering for Ocean and Landmasses
- [ ] Layering and Placement of Trees
- [ ] Landscape Details
- [ ] Collisions and Map Boundaries
- [ ] Foreground Layers
- [ ] Exporting Layers for Projects Import
